services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    networks:
      - app-network
    volumes:
      - server-data:/app/database
    environment:
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${OUTPUT_PORT}:${CLIENT_PORT}"
    networks:
      - app-network
    restart: unless-stopped

#  eml-handler:
#    image: alpine
#    volumes:
#      - ./eml-files:/app/eml-files
#    command: "sh -c 'while true; do echo Handling EML files; sleep 3600; done'"
#    networks:
#      - app-network
#    restart: unless-stopped

volumes:
  server-data:

networks:
  app-network:
    driver: bridge
