services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3007:80"
    networks:
      - app-network
    environment:
      - VITE_SERVER_URL=http://server:1234
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    networks:
      - app-network
    volumes:
      - server-data:/app/database
    environment:
      WEBSOCKET_PORT: 1234
      JWT_SECRET: your_jwt_secret
      KILL_PORT_IF_USED: "true"
    restart: unless-stopped

  eml-handler:
    image: alpine
    volumes:
      - ./eml-files:/app/eml-files
    command: "sh -c 'while true; do echo Handling EML files; sleep 3600; done'"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  server-data:

networks:
  app-network:
    driver: bridge
